---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: openweb-ui-db
  namespace: openweb-ui
  labels:
    app: openweb-ui-db
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 10Gi
