---
apiVersion: v1
kind: Service
metadata:
  name: openweb-ui-db
  namespace: openweb-ui
  labels:
    app: openweb-ui-db
spec:
  type: ClusterIP
  clusterIP: None
  selector:
    app: openweb-ui-db
  ports:
    - protocol: TCP
      port: 5432
      targetPort: 5432
