---
apiVersion: v1
kind: Service
metadata:
  name: llama3
  namespace: ollama
  labels:
    app: llama3
spec:
  selector:
    app: llama3
  ports:
    - protocol: TCP
      port: 8080
      targetPort: 11434
